"""add phone_number to patients

Revision ID: 4f807bfc7bc9
Revises: deac0ae9f150
Create Date: 2026-05-21 12:52:31.196225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f807bfc7bc9'
down_revision: Union[str, Sequence[str], None] = 'deac0ae9f150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'phone_number')
    # ### end Alembic commands ###
