"""add record_type to medical_records

Revision ID: deac0ae9f150
Revises: 0c80cef51302
Create Date: 2026-05-17 17:40:40.094415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deac0ae9f150'
down_revision: Union[str, Sequence[str], None] = '0c80cef51302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('record_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'record_type')
    # ### end Alembic commands ###
