"""add test_medicosync_user table

Revision ID: ee503a16e541
Revises: 008b34aa80c2
Create Date: 2026-08-14 17:08:56.072232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee503a16e541'
down_revision: Union[str, Sequence[str], None] = '008b34aa80c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_medicosync_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('DOCTOR', 'ADMIN', 'ASSISTANT', name='test_user_role_enum'), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='test_user_gender_enum'), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_medicosync_user_email'), 'test_medicosync_user', ['email'], unique=True)
    op.create_index(op.f('ix_test_medicosync_user_id'), 'test_medicosync_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_medicosync_user_id'), table_name='test_medicosync_user')
    op.drop_index(op.f('ix_test_medicosync_user_email'), table_name='test_medicosync_user')
    op.drop_table('test_medicosync_user')
    # ### end Alembic commands ###
